import { readFile } from 'node:fs/promises';
import { build } from 'esbuild';

const metadata = (await readFile('src/metadata.txt', 'utf8')).trim();
const version = metadata.match(/^\/\/ @version\s+(.+)$/m)?.[1];

if (!version) throw new Error('Missing @version in src/metadata.txt');

const debugMetadata = metadata
  .replace(/^\/\/ @name\s+.+$/m, '// @name         WhatsApp Web Plus Debug')
  .replace(/^\/\/ @(?:updateURL|downloadURL)\s+.+$\r?\n?/gm, '');

const loaderBootstrap = `${debugMetadata}
// Generated from src/; do not edit this file directly.
(() => {
  const loaderProperty = '__whatsappWebPlusLoader';
  if (window[loaderProperty]) return;
  const loaderState = {
    contractVersion: 1,
    scriptVersion: ${JSON.stringify(version)},
    bundleIdentifier: globalThis.__whatsappWebPlusBundleHash || 'debug',
    state: 'initializing',
    initializedAt: typeof performance !== 'undefined' && typeof performance.now === 'function'
      ? performance.now()
      : 0,
    readyStateAtInstall: document.readyState,
    errorCode: ''
  };
  Object.defineProperty(window, loaderProperty, {
    value: loaderState,
    writable: false,
    configurable: false,
    enumerable: false
  });
  try {`;

const loaderFooter = `  } catch (error) {
    loaderState.state = 'failed';
    loaderState.errorCode = error instanceof TypeError
      ? 'bootstrap.type'
      : error instanceof RangeError ? 'bootstrap.range' : 'bootstrap.exception';
    const health = Object.freeze({
      contractVersion: loaderState.contractVersion,
      scriptVersion: loaderState.scriptVersion,
      bundleIdentifier: loaderState.bundleIdentifier,
      origin: location.origin,
      topFrame: window === window.top,
      state: 'failed',
      readyStateAtInstall: loaderState.readyStateAtInstall,
      requiredNodes: Object.freeze({ settingsMenu: false, statusRegion: false, messageLog: false }),
      errorCode: loaderState.errorCode
    });
    Object.defineProperty(window, '__whatsappWebPlusLoaderHealth', {
      value: health,
      writable: false,
      configurable: true,
      enumerable: false
    });
  }
})();`;

await build({
  entryPoints: ['debug-entry.js'],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'chrome109',
  minify: false,
  sourcemap: false,
  legalComments: 'inline',
  treeShaking: false,
  define: {
    __SCRIPT_VERSION__: JSON.stringify(version),
    __BUNDLE_IDENTIFIER__: JSON.stringify('debug'),
    __DEBUG_BUILD__: 'true'
  },
  banner: { js: loaderBootstrap },
  footer: { js: loaderFooter },
  outfile: 'whatsapp_web_plus.debug.js'
});
