import { readFile } from 'node:fs/promises';
import { build } from 'esbuild';

const metadata = (await readFile('src/metadata.txt', 'utf8')).trim();
const version = metadata.match(/^\/\/ @version\s+(.+)$/m)?.[1];

if (!version) throw new Error('Missing @version in src/metadata.txt');

const debugMetadata = metadata
  .replace(/^\/\/ @name\s+.+$/m, '// @name         WhatsApp Web Plus Debug')
  .replace(/^\/\/ @(?:updateURL|downloadURL)\s+.+$\r?\n?/gm, '');

await build({
  entryPoints: ['debug-entry.js'],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'chrome109',
  minify: false,
  sourcemap: false,
  legalComments: 'inline',
  treeShaking: false,
  define: {
    __SCRIPT_VERSION__: JSON.stringify(version),
    __DEBUG_BUILD__: 'true'
  },
  banner: { js: `${debugMetadata}\n// Generated from src/; do not edit this file directly.` },
  outfile: 'whatsapp_web_plus.debug.js'
});
