import { readFile } from 'node:fs/promises';
import { build } from 'esbuild';

const metadata = (await readFile('src/metadata.txt', 'utf8')).trim();
const version = metadata.match(/^\/\/ @version\s+(.+)$/m)?.[1];

if (!version) throw new Error('Missing @version in src/metadata.txt');

await build({
  entryPoints: ['src/main.js'],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'chrome109',
  minify: false,
  sourcemap: false,
  legalComments: 'inline',
  treeShaking: false,
  define: { __SCRIPT_VERSION__: JSON.stringify(version) },
  banner: { js: `${metadata}\n// Generated from src/; do not edit this file directly.` },
  outfile: 'whatsapp_web_plus.user.js'
});
